name: Node Typescript CD

on:
  push:
    branches: [ main ]

jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14'
      - name: Installing dependencies
        run: yarn install
      - name: Building application
        run: yarn build
      - name: Generate deployment package
        run: zip -r deploy.zip * -x "**node_modules**"
      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: typescript-nodejs-app-ci-cd
          environment_name: Typescriptnodejsappcicd-env
          region: us-west-2
          version_label: "ci-cd-aws-typescript"
          deployment_package: deploy.zip

      - name: Deployed to AWS
        run: echo App deployed to ELB

